-- Manual delivery notes are durable logical ingestions even when no original
-- image exists. Photo ingestions retain the strict evidence requirements.
BEGIN;

ALTER TABLE public.ingestions
    ADD COLUMN IF NOT EXISTS source_type TEXT NOT NULL DEFAULT 'telegram_photo';

ALTER TABLE public.ingestions
    ALTER COLUMN storage_bucket DROP NOT NULL,
    ALTER COLUMN storage_bucket DROP DEFAULT,
    ALTER COLUMN storage_path DROP NOT NULL,
    ALTER COLUMN content_type DROP NOT NULL,
    ALTER COLUMN image_hash DROP NOT NULL,
    ALTER COLUMN byte_size SET DEFAULT 0;

-- This name is generated by PostgreSQL for the inline CHECK in migration 001.
ALTER TABLE public.ingestions
    DROP CONSTRAINT IF EXISTS ingestions_byte_size_check;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.ingestions'::regclass
          AND conname = 'ingestions_source_type_valid'
    ) THEN
        ALTER TABLE public.ingestions ADD CONSTRAINT ingestions_source_type_valid
            CHECK (source_type IN ('telegram_photo','manual'));
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'public.ingestions'::regclass
          AND conname = 'ingestions_source_evidence_valid'
    ) THEN
        ALTER TABLE public.ingestions ADD CONSTRAINT ingestions_source_evidence_valid CHECK (
            (
                source_type = 'telegram_photo'
                AND byte_size > 0
                AND storage_bucket IS NOT NULL AND btrim(storage_bucket) <> ''
                AND storage_path IS NOT NULL AND btrim(storage_path) <> ''
                AND content_type IS NOT NULL AND btrim(content_type) <> ''
                AND image_hash IS NOT NULL AND image_hash ~ '^[0-9a-f]{64}$'
            )
            OR
            (
                source_type = 'manual'
                AND (
                    (
                        byte_size = 0
                        AND storage_bucket IS NULL
                        AND storage_path IS NULL
                        AND content_type IS NULL
                        AND image_hash IS NULL
                    )
                    OR
                    (
                        byte_size > 0
                        AND storage_bucket IS NOT NULL AND btrim(storage_bucket) <> ''
                        AND storage_path IS NOT NULL AND btrim(storage_path) <> ''
                        AND content_type IS NOT NULL AND btrim(content_type) <> ''
                        AND image_hash IS NOT NULL AND image_hash ~ '^[0-9a-f]{64}$'
                    )
                )
            )
        );
    END IF;
END $$;

DROP INDEX IF EXISTS public.uq_ingestions_exact_image;
CREATE UNIQUE INDEX uq_ingestions_exact_image
    ON public.ingestions(image_hash) WHERE image_hash IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_ingestions_source_status
    ON public.ingestions(source_type, status, received_at);

INSERT INTO public.audit_events (actor_type, actor_id, event_type, data)
VALUES ('migration', '002_manual_ingestions', 'schema.manual_ingestions_enabled',
        jsonb_build_object('manual_without_image', true))
ON CONFLICT DO NOTHING;

COMMIT;
